### ISSUE TITLE
We shouldn't be using `urlencoded` in requests, rather only `json` as its simple to handle.

### ISSUE THREAD

**Issue by drigio** [Zeal-Student-Developers/issue-tracker#16]
`www-x-form-urlencoded` is a bit of PITA to work with. Also majority of the current api set work with `application/json` type of data and is simpler, easy to read and faster.

**Comment by FaiyazMujawar** [comment]
I suggest keeping the `urlencoded` format as the Web-app front end might require the same.

**Comment by drigio** [comment]
Please give use cases to support your argument, so that we can identify those regions
