### ISSUE TITLE
Create loaders for express app, mongodb connection and other middlewares.

### ISSUE THREAD

**Issue by drigio** [Zeal-Student-Developers/issue-tracker#33]
Currently our express app and server listens on in the same file. This hampers testability and modularity. Also mongoose connection also needs to be called on demand. 
For further info look at https://softwareontheroad.com/ideal-nodejs-project-structure/#loaders

**Comment by drigio** [comment]
@FaiyazMujawar Would you like to work on this next? I think this is crucial for us, so that we can setup integration tests and CI/CD for our project. Please look into this and if you have any specific questions, please ask them here.

**Comment by FaiyazMujawar** [comment]
Do you have any resources to look forward to for this?? A youtube video or something?? Might help me getting it done.

**Comment by drigio** [comment]
Check the link in the description. Also you can just look at any integration test video which has mongodb and nodejs api

**Comment by FaiyazMujawar** [comment]
I'll see if I can find anything.
