### ISSUE TITLE
User identity leak in the JWT token

### ISSUE THREAD

**Issue by FaiyazMujawar** [Zeal-Student-Developers/issue-tracker#37]
In the current implementation, the JWT token contains the zprn of the student. Anyone who has the access to the JWT token, can decode the identity of the user using the zprn. 

Hence, I suggest that we store the `_id` of the mongodb document for the same user in the JWT token. This way out would be made sure that no-one can identify the user.

**Comment by drigio** [comment]
Sure. We should do this. I didn't think of this before.
