### ISSUE TITLE
Module to import the students data from a csv for creating user profiles based on them to reduce manual work.

### ISSUE THREAD

**Issue by drigio** [Zeal-Student-Developers/issue-tracker#50]
[TODO] Add Desc.

**Comment by FaiyazMujawar** [comment]
I think this functionality should be implemented on the front end. The API provides an endpoint `api/users/add` to create a new user accessible only to authorized users. The front-end can make read the CSV file on the client machine and make multiple calls for each user to the API on specified endpoint to create the user. What say?

**Comment by drigio** [comment]
Yes this can be done on the front-end as well. We can however have a separate route, that can take a csv, parse it and create new users. Frontend might face issues regarding this, but I guess the server might handle it properly. This is a late addition and we can discuss more about it and find an optimal approach.

**Comment by drigio** [comment]
I guess this has already been addressed in #61 . Will be closing if there is nothing more to add to it.
