### ISSUE TITLE
Get issue returns entire document

### ISSUE THREAD

**Issue by FaiyazMujawar** [Zeal-Student-Developers/issue-tracker#56]
In the current implementation, when a request for issue(s) is sent to the API, the API returns entire mongodb document, which is not desirable. Only the required must be sent.

**Comment by FaiyazMujawar** [comment]
In the current implementation, on recieving a request for `issues`, the API returns the following data
```JSON
{
  "_id":"ID of issue",
  "title":"title",
  "description":"description",
  "section":"section",
  "department":"department",
  "scope":"scope",
  "images": [],
  "upvotes":"count of upvotes",
  "upvoters": [],
  "comments": [],
  "solutions": [],
  "isEdited":"whether issue is edited",
  "isInappropriate":"whether is inappropriate",
  "isResolved":"whether resolved",
  "createdOn":"date",
  "createdBy": "Author of issue"
}
```

According to me, the following fields may not be send to the client:

- `isDeleted`
- `createdBy`, a potential identity leak
- `upvoters`, since it contains the ID of the users upvoting it, a potential identity leak
  
Instead, I propose sending the following data to the client
```JSON
{
  "_id":"ID of issue",
  "title":"title",
  "description":"description",
  "section":"section",
  "department":"department",
  "scope":"scope",
  "images": [],
  "upvotes":"count of upvotes",
  "isUpvoted": "whether the user has already upvoted the issue",
  "comments": [],
  "solutions": [],
  "isEdited":"whether issue is edited",
  "isInappropriate":"whether is inappropriate",
  "isResolved":"whether resolved",
  "createdOn":"date",
  "isAuthor": "Whether the current user is author of the issue"
}
```

This would remove any possibility of identity leak.

**Comment by drigio** [comment]
This is very detailed! Looks good.
